cors:
  allowed-origin-patterns: https://teacher-agent-nine.vercel.app

server:
  tomcat:
    threads:
      max: 20
      min-spare: 5

spring:
  main:
    lazy-initialization: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
